version: '3.7'

services:
### Workspace Utilities ##################################
    # workspace:

### PHP-FPM ##############################################
    # php-fpm:

### NGINX Server #########################################
    nginx:
        ports:
            - "80:80"
            - "443:443"

### MySQL ################################################
    mysql:
      ports:
        - "3306:3306"

### Redis ################################################
    # redis:

### Laravel Echo Server #######################################
    laravel-echo-server:
      ports:
        - "6001:6001"