version: '3.7'

services:

### App #######################################
    app:
      command: "yarn serve -p 9091"

### Admin #####################################
    admin:
      command: "yarn serve -p 9092"